name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Git repository
      #   uses: actions/checkout@v4
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: https://git@git.overleaf.com/660d604d58b9b8e7e8fc6d6c
          token: ${{ secrets.OVERLEAF }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
